[settings]
idiomatic_version_file_enable_tools = ["ruby"]

[tool_alias]
pi = "github:earendil-works/pi"
opencode = "github:anomalyco/opencode"

[tools]
bun = "latest"
ruby = "latest"
pnpm = "latest"
nodejs = "lts"
uv = "latest"
python = "3.14"
rust = "latest"
usage = "latest"
opencode = "latest"
pi = "latest"
