add_newline = true
command_timeout = 200

format = """
$directory\
$git_branch\
$git_status\
$cmd_duration\
$line_break\
$character"""

[character]
success_symbol = '[λ](bold green)'
error_symbol = '[λ](bold red)'

[directory]
style = "bold blue"
truncate_to_repo = false

[git_branch]
format = "[$branch(:$remote_branch)]($style) "
style = "italic purple"
