#:schema https://dinky.rodeo/schemas/dinky.json

start-at-login = true
workspaces = 5
default-layout = 'tiles'
follow-app-activation = true

[accordion]
padding = 30
orientation = 'auto'

[gaps]
inner = 12
outer = 8

[borders]
enabled = true
width = 3
active-color = '#8aadf4ee'
inactive-color = '#eeeeee55'
exclude-apps = ['pl.maketheweb.cleanshotx']

[focus-follows-mouse]
enabled = false
delay-ms = 100
accordion-edges = true

[animations]
enabled = true
duration-ms = 150

[[rules]]
app-id = 'com.apple.systempreferences'
run = 'layout floating'

[[rules]]
app-id = 'com.apple.finder'
run = 'layout floating'

[[rules]]
app-id = 'com.apple.Preview'
run = 'layout floating'

[[rules]]
app-id = 'com.apple.QuickTimePlayerX'
run = 'layout floating'

# SUPER = Control + Option + Command (ctrl-alt-cmd).
[mode.main]
ctrl-alt-cmd-1 = 'workspace 1'
ctrl-alt-cmd-2 = 'workspace 2'
ctrl-alt-cmd-3 = 'workspace 3'
ctrl-alt-cmd-4 = 'workspace 4'
ctrl-alt-cmd-5 = 'workspace 5'
ctrl-alt-cmd-6 = 'workspace 6'
ctrl-alt-cmd-7 = 'workspace 7'
ctrl-alt-cmd-8 = 'workspace 8'
ctrl-alt-cmd-9 = 'workspace 9'
ctrl-alt-cmd-shift-1 = 'move-window-to-workspace 1'
ctrl-alt-cmd-shift-2 = 'move-window-to-workspace 2'
ctrl-alt-cmd-shift-3 = 'move-window-to-workspace 3'
ctrl-alt-cmd-shift-4 = 'move-window-to-workspace 4'
ctrl-alt-cmd-shift-5 = 'move-window-to-workspace 5'
ctrl-alt-cmd-shift-6 = 'move-window-to-workspace 6'
ctrl-alt-cmd-shift-7 = 'move-window-to-workspace 7'
ctrl-alt-cmd-shift-8 = 'move-window-to-workspace 8'
ctrl-alt-cmd-shift-9 = 'move-window-to-workspace 9'
ctrl-alt-cmd-tab = 'workspace next'
ctrl-alt-cmd-shift-tab = 'workspace prev'
ctrl-alt-cmd-backtick = 'workspace-back-and-forth'
ctrl-alt-cmd-left = 'focus left'
ctrl-alt-cmd-down = 'focus down'
ctrl-alt-cmd-up = 'focus up'
ctrl-alt-cmd-right = 'focus right'
ctrl-alt-cmd-shift-left = 'move left'
ctrl-alt-cmd-shift-down = 'move down'
ctrl-alt-cmd-shift-up = 'move up'
ctrl-alt-cmd-shift-right = 'move right'
ctrl-alt-cmd-minus = 'resize smart -50'
ctrl-alt-cmd-equal = 'resize smart +50'
ctrl-alt-cmd-f = 'fullscreen'
ctrl-alt-cmd-t = 'layout floating tiling'
ctrl-alt-cmd-l = 'layout accordion tiles'
ctrl-alt-cmd-shift-n = 'move-window-to-display next'
