## Primer dark base scales
## https://github.com/primer/primitives/blob/main/src/tokens/base/color/dark/dark.json5

# black     → neutral.7 (#3d444d)
# red       → red.3
# green     → green.3
# yellow    → yellow.3
# blue      → blue.3
# magenta   → purple.3
# cyan      → teal.6
# white     → neutral.10
# br.black  → neutral.8
# br.red    → red.2
# br.green  → green.2
# br.yellow → yellow.2
# br.blue   → blue.2
# br.magenta→ purple.2
# br.cyan   → teal.7
# br.white  → white (#ffffff)

palette = 0=#3d444d
palette = 1=#ff7b72
palette = 2=#3fb950
palette = 3=#d29922
palette = 4=#58a6ff
palette = 5=#be8fff
palette = 6=#1cb0ab
palette = 7=#b7bdc8
palette = 8=#656c76
palette = 9=#ffa198
palette = 10=#56d364
palette = 11=#e3b341
palette = 12=#79c0ff
palette = 13=#d2a8ff
palette = 14=#1fbdb2
palette = 15=#ffffff
background = #0d1117
foreground = #f0f6fc
cursor-color = #388bfd
cursor-text = #79c0ff
selection-background = #f0f6fc
selection-foreground = #0d1117
