## Primer light base scales
## https://github.com/primer/primitives/blob/main/src/tokens/base/color/light/light.json5

# black     → black (#1f2328)
# red       → red.5
# green     → green.6
# yellow    → yellow.8
# blue      → blue.5
# magenta   → purple.5
# cyan      → teal.5
# white     → neutral.8
# br.black  → neutral.9
# br.red    → red.6
# br.green  → green.5
# br.yellow → yellow.7
# br.blue   → blue.4
# br.magenta→ purple.4
# br.cyan   → teal.4
# br.white  → neutral.7

palette = 0=#1f2328
palette = 1=#cf222e
palette = 2=#116329
palette = 3=#4d2d00
palette = 4=#0969da
palette = 5=#8250df
palette = 6=#127e81
palette = 7=#818b98
palette = 8=#59636e
palette = 9=#a40e26
palette = 10=#1a7f37
palette = 11=#633c01
palette = 12=#218bff
palette = 13=#a475f9
palette = 14=#179b9b
palette = 15=#c8d1da
background = #ffffff
foreground = #1f2328
cursor-color = #0969da
cursor-text = #54aeff
selection-background = #1f2328
selection-foreground = #ffffff
